---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-playground
        component: test-app
    spec:
      containers:
      - name: test-app
        image: thomasraynal/kubernetesplayground:v1
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5  
        #   periodSeconds: 10
        envFrom:
          - configMapRef: 
              name: config
        imagePullPolicy : Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-playground
        component: test-api
    spec:
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'sleep 30;'] #waiting for mongo pod to boot
      containers:
      - name: test-api
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        #   periodSeconds: 10
        image: thomasraynal/kubernetesplayground-api:v1
        envFrom:
          - configMapRef: 
              name: config
        imagePullPolicy : Always
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-server-proxy
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: gateway
    image: luksa/kubectl-proxy:1.8.0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-playground
        component: mongodb
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
      containers:
      - image: mongo
        name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        ports:
        - containerPort: 27017
          protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config 
  labels:
    app: kubernetes-playground  
data:
  ASPNETCORE_URLS: http://0.0.0.0:80
  MONGO_URI: mongodb://mongodb:27017
  MONGO_DATABASE: test