version: '3.4'

services:
  test:
    image: thomasraynal/kubernetesplayground:v1
    build: 
     context: .
     dockerfile: ./KubernetesPlayground/Dockerfile
  test-api:
    image: thomasraynal/kubernetesplayground-api:v1
    build: 
     context: .
     dockerfile: ./KubernetesPlayground.Api/Dockerfile
  persistent-app:
    image: thomasraynal/kubernetesplaygroundperistentapp:v1
    build: 
     context: .
     dockerfile: ./KubernetesPlayground.PersistentApp/Dockerfile



