---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: kubernetes-playground
    component: test-app
---
apiVersion: v1
kind: Service
metadata:
  name: test-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: kubernetes-playground
    component: test-api
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - name: c1
    port: 27017
  selector:
    app: kubernetes-playground
    component: mongodb